services:
  backend:
    build: ./backend
    container_name: backend
    ports:
      - "3002:3002"
    environment:
      PORT: 3002
      AWS_REGION:
      AWS_ACCESS_KEY_ID:
      AWS_SECRET_ACCESS_KEY:
      PRODUCT_TABLE:
      ANALYTICS_TABLE:
      PRODUCT_QUEUE_URL:
    networks:
      - app-network

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "8080:80"
    environment:
      VITE_BASE_URL: http://localhost:3002
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

