openapi: 3.1.0
info:
  title: Product Management System API
  version: 1.0.0
  description: API for managing products, including create, update, delete, import, and export operations.

paths:
  /product:
    post:
      summary: Create a product
      description: Create a new product and emit an event to calculate stats.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProductCreateRequest'
      responses:
        '200':
          description: Product created successfully
          content:
            application/json:
              schema:
                type: string
                example: "Product created successfully"

  /products/{productId}:
    put:
      summary: Update a product
      description: Update a product by ID, emit an event to calculate stats and low stock warning.
      parameters:
        - name: productId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProductUpdateRequest'
      responses:
        '200':
          description: Product updated successfully
          content:
            application/json:
              schema:
                type: string
                example: "Product updated successfully"

    delete:
      summary: Delete a product
      description: Delete a product by ID.
      parameters:
        - name: productId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Product deleted successfully
          content:
            application/json:
              schema:
                type: string
                example: "Product deleted successfully"

  /products:
    get:
      summary: Get products by seller
      description: Retrieve all products belonging to a seller.
      responses:
        '200':
          description: List of products
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ProductResponse'

  /products/import:
    post:
      summary: Import products from CSV
      description: Upload a CSV file to import multiple products.
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
      responses:
        '200':
          description: Products imported successfully
          content:
            application/json:
              schema:
                type: string
                example: "Products imported successfully"

  /products/export:
    get:
      summary: Export products to CSV
      description: Download products as a CSV file.
      responses:
        '200':
          description: CSV file download
          content:
            text/csv:
              schema:
                type: string
                format: binary

components:
  schemas:
    ProductCreateRequest:
      type: object
      required:
        - name
        - description
        - quantity
        - price
        - categoryId
      properties:
        name:
          type: string
        description:
          type: string
        quantity:
          type: integer
        price:
          type: number
          format: float
        categoryId:
          type: string

    ProductUpdateRequest:
      type: object
      properties:
        name:
          type: string
        description:
          type: string
        quantity:
          type: integer
        price:
          type: number
          format: float
        categoryId:
          type: string

    ProductResponse:
      type: object
      properties:
        productId:
          type: string
        name:
          type: string
        description:
          type: string
        quantity:
          type: integer
        price:
          type: number
          format: float
        categoryId:
          type: string
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time